In [78]:
import pandas as pd
import math

In [79]:
def relative_humidity(temp_c, dew_point_c):
    numerator = math.exp((17.67 * dew_point_c) / (dew_point_c + 243.5))
    denominator = math.exp((17.67 * temp_c) / (temp_c + 243.5))
    rh = 100 * (numerator / denominator)
    return rh

In [80]:
df = pd.read_csv("metar_only_raw_2021_01.csv")

In [81]:
df.head()

,Time,Wind,Visibility,Temperature,Sea Level Pressure,Rain,Year,Month
0,312200Z,VRB02KT,8000.0,27/26,Q1010,NO,2021,1
1,312000Z,VRB01KT,8000.0,28/26,Q1010,NO,2021,1
2,311900Z,VRB02KT,7000.0,28/26,Q1009,NO,2021,1
3,311800Z,VRB03KT,6000.0,29/25,Q1008,NO,2021,1
4,311700Z,21004KT,6000.0,30/24,Q1007,NO,2021,1

In [82]:
df.tail()

,Time,Wind,Visibility,Temperature,Sea Level Pressure,Rain,Year,Month
709,010500Z,00000KT,6000.0,25/25,Q1010,NO,2021,1
710,010400Z,00000KT,6000.0,25/25,Q1009,NO,2021,1
711,010300Z,05002KT,6000.0,25/25,NaN,NO,2021,1
712,010200Z,05002KT,2500.0,26/26,Q1009,NO,2021,1
713,010000Z,00000KT,7000.0,26/26,Q1010,NO,2021,1

In [83]:
df = df[::-1].reset_index(drop=True)

In [84]:
df.head()

,Time,Wind,Visibility,Temperature,Sea Level Pressure,Rain,Year,Month
0,010000Z,00000KT,7000.0,26/26,Q1010,NO,2021,1
1,010200Z,05002KT,2500.0,26/26,Q1009,NO,2021,1
2,010300Z,05002KT,6000.0,25/25,NaN,NO,2021,1
3,010400Z,00000KT,6000.0,25/25,Q1009,NO,2021,1
4,010500Z,00000KT,6000.0,25/25,Q1010,NO,2021,1

In [85]:
df.tail()

,Time,Wind,Visibility,Temperature,Sea Level Pressure,Rain,Year,Month
709,311700Z,21004KT,6000.0,30/24,Q1007,NO,2021,1
710,311800Z,VRB03KT,6000.0,29/25,Q1008,NO,2021,1
711,311900Z,VRB02KT,7000.0,28/26,Q1009,NO,2021,1
712,312000Z,VRB01KT,8000.0,28/26,Q1010,NO,2021,1
713,312200Z,VRB02KT,8000.0,27/26,Q1010,NO,2021,1

In [86]:
#df = df.drop(columns=['Month'])

In [87]:
df.tail()

,Time,Wind,Visibility,Temperature,Sea Level Pressure,Rain,Year,Month
709,311700Z,21004KT,6000.0,30/24,Q1007,NO,2021,1
710,311800Z,VRB03KT,6000.0,29/25,Q1008,NO,2021,1
711,311900Z,VRB02KT,7000.0,28/26,Q1009,NO,2021,1
712,312000Z,VRB01KT,8000.0,28/26,Q1010,NO,2021,1
713,312200Z,VRB02KT,8000.0,27/26,Q1010,NO,2021,1

In [88]:
len(df)

714

In [89]:
df["Time"][0][:2]

'01'

In [90]:
df["Time"][0][2:-1]

'0000'

In [91]:
df["Wind"][0]

'00000KT'

In [92]:
df["Wind"][0][-4:-2]

'00'

In [93]:
df["Temperature"][10]

'33/25'

In [94]:
df["Temperature"][10][:2]

'33'

In [95]:
df["Temperature"][10][-2:]

'25'

In [96]:
df["Sea Level Pressure"][10]

'Q1010'

In [97]:
df["Sea Level Pressure"][10][1:]

'1010'

In [98]:
Days = []
Hours = []
Temp = []
DP = []
RH = []
Wind_Speed =[]
Pressure = []
RH = []

In [99]:
for i in range(0, len(df)):
    day = df["Time"][i][:2]
    Days.append(day)
    hour = df["Time"][i][2:-1]
    Hours.append(hour)
    temp = int(df["Temperature"][i][:2])
    Temp.append(temp)
    dp = int(df["Temperature"][i][-2:])
    DP.append(dp)
    rh = relative_humidity(temp, dp)
    RH.append(rh)
    val = df["Wind"][i]
    if pd.notnull(val):
        wind_speed = str(val)[-4:-2]
    else:
        wind_speed = None
    Wind_Speed.append(wind_speed)
    value = df["Sea Level Pressure"][i]
    pressure = str(value)[1:] if pd.notnull(value) else None
    Pressure.append(pressure)

In [100]:
df["Day"] = Days

In [101]:
df["Hour"] = Hours

In [102]:
df["Temp"] = Temp

In [103]:
df["DP"] = DP

In [104]:
df["RH"] = RH

In [105]:
df["Wind Speed"] = Wind_Speed

In [106]:
df["Pressure"] = Pressure

In [107]:
df.head()

,Time,Wind,Visibility,Temperature,Sea Level Pressure,Rain,Year,Month,Day,Hour,Temp,DP,RH,Wind Speed,Pressure
0,010000Z,00000KT,7000.0,26/26,Q1010,NO,2021,1,01,0000,26,26,100.0,00,1010
1,010200Z,05002KT,2500.0,26/26,Q1009,NO,2021,1,01,0200,26,26,100.0,02,1009
2,010300Z,05002KT,6000.0,25/25,NaN,NO,2021,1,01,0300,25,25,100.0,02,None
3,010400Z,00000KT,6000.0,25/25,Q1009,NO,2021,1,01,0400,25,25,100.0,00,1009
4,010500Z,00000KT,6000.0,25/25,Q1010,NO,2021,1,01,0500,25,25,100.0,00,1010

In [109]:
valid_data = df[["Year", "Month", "Day", "Hour","Temp", "DP", "RH", "Wind Speed","Visibility"]]

In [110]:
valid_data.head()

   Year  Month Day  Hour  Temp  DP     RH Wind Speed  Visibility
0  2021      1  01  0000    26  26  100.0         00      7000.0
1  2021      1  01  0200    26  26  100.0         02      2500.0
2  2021      1  01  0300    25  25  100.0         02      6000.0
3  2021      1  01  0400    25  25  100.0         00      6000.0
4  2021      1  01  0500    25  25  100.0         00      6000.0

In [111]:
valid_data.tail()

     Year  Month Day  Hour  Temp  DP         RH Wind Speed  Visibility
709  2021      1  31  1700    30  24  70.267372         04      6000.0
710  2021      1  31  1800    29  25  79.039246         03      6000.0
711  2021      1  31  1900    28  26  88.904448         02      7000.0
712  2021      1  31  2000    28  26  88.904448         01      8000.0
713  2021      1  31  2200    27  26  94.268660         02      8000.0

In [ ]:
Days[:5]

In [ ]:
Hours[:5]

In [ ]:
Temp[:15]

In [ ]:
DP[:15]

In [ ]:
relative_humidity(25, 20)

In [ ]:
Wind_Speed[:5]

In [ ]:
Pressure[:5]

In [ ]:
RH[:10]